### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  カスタム関数のエラーコード。 関数を呼び出したセルにエラーコードが表示されます。


  これらのエラーコードに加えて、カスタムエラーメッセージが表示されます。 カスタムメッセージはエラーインジケーターメニューに表示されます。このメニューには、エラーが発生した各セルのエラーフラグの上にマウスカーソルを置くことでアクセスします。
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、使用される関数が0または空のセルで除算されていることを示します。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数名に入力ミスがあることを示しています。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数内の数値に問題があることを示しています。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数が無効なセルを参照していることを示します。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数の値が正しくないデータ型であることを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数またはサービスを使用できないことを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数内の範囲が交差していないことを示します。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
metadata:
  ms.openlocfilehash: 7136ddf8accdca9a80f9529f0594b36f38f4c63d
  ms.sourcegitcommit: 3bab97ab3b91da7cca497f6fc895408a76bd8b46
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 11/18/2020
  ms.locfileid: "49231018"
